### ISSUE TITLE
controller？

### ISSUE THREAD

**Issue by ExitPath** [MSilva98/MultiGoal_Nav_Mobile_Robot_HRL#1]
Hello, where can I find the controller module?

from controller import Robot, Motor, DistanceSensor, Supervisor

**Comment by MSilva98** [comment]
Hi, these scripts are intended to use inside the Webots Cyberbotics robot simulation software, which already has the controller. Find more info here https://cyberbotics.com/doc/reference/supervisor?tab-language=python#supervisor
